name: prisma-security-rules
services:
  postgres:
    image: postgres
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
